### ISSUE TITLE
Are there any plans for adding http image support?

### ISSUE THREAD

**Issue by teusemanuel** [tylersuehr7/chips-input-layout#13]
I would like to use Glide to pull the images from URL's and Firebase. Are there any plans to support this?

Thank you!

**Comment by tylersuehr7** [comment]
I didn't really have plans for that, but I can try to incorporate something that will let you use those image loading libraries though!

**Comment by teusemanuel** [comment]
that would be awesome! Would help me a lot have access to imageView to incorporate image loading libraries

**Comment by tylersuehr7** [comment]
The newest build I'm working on for this project will definitely include the ability to use image rendering libraries like Picasso, Glide, or whatnot!!
