### ISSUE TITLE
Unable to import library project using Gradle

### ISSUE THREAD

**Issue by 21rupeshpatil** [tylersuehr7/chips-input-layout#16]
After following steps to import your library i am getting error
 Failed to resolve: com.github.tylersuehr7:chips-input-layout:2.0
Any help would be appreciate. Thanks in Advance.

lines included in project :
project level build.gradle
`maven { url "https://jitpack.io" }`

 app level build.gradle
`compile 'com.github.tylersuehr7:chips-input-layout:2.0'`

**Comment by erichlotto** [comment]
Had the same issue, falling back to v1.3 solved the issue:
`` compile 'com.github.tylersuehr7:chips-input-layout:1.3'``

**Comment by tylersuehr7** [comment]
Thanks for letting me know about this issue! It seems that JitPack wasn't able to compile version 2.0.

I'll try to resolve this issue as soon as possible; it may just be because I updated the Gradle version

**Comment by 21rupeshpatil** [comment]
@erichlotto and @tylersuehr7 Thank you very much for the prompt reply. @tylersuehr7  Looking forward to implement 2.0. Great Work

**Comment by Kodak1234** [comment]
I am experiencing the same problem.

**Comment by tylersuehr7** [comment]
Try using chips-input-layout:2.2, that should fix the not being resolved issue.

For some reason when I previously let my Android Studio update my Gradle version, it commented out the entire gradlew file and that's what was causing Jitpack.io to not be able to build the library

**Comment by 21rupeshpatil** [comment]
Thanks @tylersuehr7 . Working Perfectly Now. Keep Doing Great Work.
