### ISSUE TITLE
Change ChipsInputLayout inputType

### ISSUE THREAD

**Issue by erichlotto** [tylersuehr7/chips-input-layout#17]
Seems like the input type in the ChipsInputLayout is locked and can`t use predictions. I want my users to create custom tags for contents so predictions and autocorrect are very nice features to have.

**Comment by tylersuehr7** [comment]
Hey thanks for telling me about this issue, in the next release I'll add a method to allow the input type to be changed on the internal EditText using by ChipsInputLayout.

**Comment by tylersuehr7** [comment]
I've updated support for this feature in this release 2.3:

Using `ChipsInputLayout#setInputType(int)` will allow you to change the input type on the internal `ChipsEditText`. Also, I've added a getter for that value as well: `ChipsInputLayout#getInputType()` : int.
