### ISSUE TITLE
Setting Show Details to False Causes Crash

### ISSUE THREAD

**Issue by dangaffey** [tylersuehr7/chips-input-layout#20]
On Line 228 of **ChipsAdapter.java**, you are setting either the adapter as the listener, or null, depending upon the selection for mShowDetails.  If you look at your implementation of that function '_setOnChipClicked_' on Line 103 of **ChipView.java** you'll see this creates a null pointer exception.  You are setting an onClick listener regardless of the parameter's value, which calls on that parameter's expected 'onChipClicked' method, which if that listener is null... Kaboom.

**Comment by tylersuehr7** [comment]
Good find! I'll try to get an update to fix this as soon as possible!

**Comment by tylersuehr7** [comment]
I put a fix in release 2.3 for this, thanks again!
