### ISSUE TITLE
Keyboard hides and warns inactive inputconnection

### ISSUE THREAD

**Issue by gokrish6670** [tylersuehr7/chips-input-layout#6]
keyboard hide on every click in filterablechip list.. how to prevent 
![image](https://user-images.githubusercontent.com/22348175/32038535-08095666-ba48-11e7-8755-493c46d39c64.png)

**Comment by gokrish6670** [comment]
i found there is hidekeyboard method in filteredlist click.. can u disable that

**Comment by tylersuehr7** [comment]
Hiding the keyboard when the filtered list chip is clicked is the intended functionality, but in the next release there will be an option to toggle hiding the keyboard or not
