### ISSUE TITLE
XML example in Readme should be updated

### ISSUE THREAD

**Issue by d34n0s** [tylersuehr7/chips-input-layout#9]
Hey Mate,

Thanks for making the library available. Just a minor thing. In your readme XML example you have 

<com.tylersuehr.library.ChipsInputLayout
        android:id="@+id/chips_input"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:hint="Start typing for chips... "
        android:textColorHint="#757575"
        android:textColor="#212121"
        app:detailedChipsEnabled="true"
        app:customChipsEnabled="true"/>

Which is fine for the way you have setup your example app where the library is local in a folder.

But if you add the library via gradle, then you need to use 

<com.tylersuehr.chips.ChipsInputLayout
        android:id="@+id/chips_input"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:hint="Start typing for chips... "
        android:textColorHint="#757575"
        android:textColor="#212121"
        app:detailedChipsEnabled="true"
        app:customChipsEnabled="true"/>

**Comment by tylersuehr7** [comment]
Thanks for telling me about this issue, I've just updated it now!
